apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: webserver-{{.Replica}}-{{.Iteration}}
  name: webserver-pvc-{{.Replica}}-{{.Iteration}}
spec:
  storageClassName: {{.csiRWX}}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100M
