kind: Service
apiVersion: v1
metadata:
  name: webserver-{{.Replica}}-{{.Iteration}}
spec:
  selector:
    name: webserver-{{.Replica}}-{{.Iteration}}
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
