kind: Deployment
apiVersion: apps/v1
metadata:
  name: webserver-{{.Replica}}-{{.Iteration}}
spec:
  template:
    metadata:
      labels:
        name: webserver-{{.Replica}}-{{.Iteration}}
    spec:
      nodeSelector: {{.nodeSelector}}
      initContainers:
      - name: install
        image: quay.io/wolfgangntnx/pgbench/busybox:latest
        command: ["/bin/sh", "-c","[ ! -e 'var/www/index.html' ] && echo 'INDEX' >> /var/www/index.html "]
        volumeMounts:
        - name: webserver-pvc-{{.Replica}}-{{.Iteration}}
          mountPath: "/var/www"
      containers:
      - name: webserver
        image: quay.io/wolfgangntnx/pgbench/web:latest
        resources:
          requests:
            memory: "10Mi"
            cpu: "10m"
        volumeMounts:
        - mountPath: /var/www
          name: webserver-pvc-{{.Replica}}-{{.Iteration}}
        ports:
        - containerPort: 3000
          protocol: TCP
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
      volumes:
      - name: webserver-pvc-{{.Replica}}-{{.Iteration}}
        persistentVolumeClaim:
          claimName: webserver-pvc-{{.Replica}}-{{.Iteration}}
      restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      name: webserver-{{.Replica}}-{{.Iteration}}
  triggers:
  - type: ConfigChange
  strategy:
    type: RollingUpdate
