global:
  writeToFile: false
  createTarball: false
  indexerConfig:
    enabled: true
    esServers: [https://elastic:{{ .esPassword }}@{{ .esRoute }}]
    insecureSkipVerify: true
    defaultIndex: kube-burner
    type: elastic
  measurements:
    - name: podLatency
      esIndex: kube-burner

jobs:
  - name: combined
    namespaceLabels:
        security.openshift.io/scc.podSecurityLabelSync: false
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    jobIterations: {{ .JOB_ITERATIONS}}
    qps: {{ .QPS}}
    burst: {{ .QPS}}
    namespacedIterations: true
    namespace: combined
    waitWhenFinished: true
    jobPause: 180s
    podWait: false
    objects:
      - objectTemplate: templates/postgres-pvc.yml
        replicas: 1

      - objectTemplate: templates/postgres-deployment.yml
        replicas: 1
        inputVars:
          nodeSelector: "${POD_NODE_SELECTOR}"

      - objectTemplate: templates/postgres-service.yml
        replicas: 1

      - objectTemplate: templates/app-deployment.yml
        replicas: 1
        inputVars:
          nodeSelector: "${POD_NODE_SELECTOR}"

      - objectTemplate: webserver-deployment.yml
        replicas: 3
        inputVars:
          nodeSelector: "${POD_NODE_SELECTOR}"

      - objectTemplate: webserver-service.yml
        replicas: 1

      - objectTemplate: curl-deployment.yml
        replicas: 1
        inputVars:
          nodeSelector: "${POD_NODE_SELECTOR}"

